import { Component } from '@angular/core';

@Component({
  selector: 'app-main-layout',
  templateUrl: './main-layout.component.html',
  styleUrls: ['./main-layout.component.scss'],
})
export class MainLayoutComponent {
  inputData = [
    {
      icon: 'assets/images/pencil.svg',
      textColor: 'secondary-color',
      headingClr: 'secondary-color',
      bg: 'primary-bg',
      iconBg: 'secondary-bg',
      heading: 'Premium Quality',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      icon: 'assets/images/Vector (1).svg',
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Private & Confidential',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      icon: 'assets/images/Vector (1).svg',
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'On Time Delivery',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      icon: 'assets/images/Vector (5).svg',
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Online Order Tracking',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      icon: 'assets/images/Vector (3).svg',
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Unlimited Revisions & Edits',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      icon: 'assets/images/Vector (4).svg',
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Friendly Customer Support',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
  ];
  inputDataSlide = [
    {
      textColor: 'secondary-color',
      headingClr: 'secondary-color',
      countClr:'',
      bg: 'primary-bg',
      iconBg: 'secondary-bg',
      heading: 'Premium Quality',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      countClr:'secondary-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Private & Confidential',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      countClr:'secondary-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'On Time Delivery',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      countClr:'secondary-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Online Order Tracking',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      countClr:'secondary-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Unlimited Revisions & Edits',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
    {
      textColor: 'light-text-color',
      headingClr: 'dark-text-color',
      countClr:'secondary-color',
      bg: 'secondary-bg',
      iconBg: 'primary-bg',
      heading: 'Friendly Customer Support',
      text: 'World-class native English-speaking writers with advanced degrees at elite U.S. schools. We have expertise in all academic subjects. All writing is custom content and high quality.    ',
    },
  ];
}
